config/routes.rb
Rails.application.routes.draw do
  resources :checkatris
  resources :reportes
  resources :clienteremis
  resources :licenses
  resources :hojavidas
  resources :remisions, except: [:delete]
  devise_for :users

  root 'inicio#index'

  resources :checkatris do
    collection do
      post :import
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :hojavida
  has_one_attached :file
end

app/models/atricheck.rb
class Atricheck < ApplicationRecord
  belongs_to :checkatri
  belongs_to :remision


end

app/models/atriremi.rb
class Atriremi < ApplicationRecord
  belongs_to :remision

end

app/models/checkatri.rb
class Checkatri < ApplicationRecord
  has_many :atrichecks

  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true


  def name
    "#{referencia} - #{descripcion}"
  end

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |checkatri|
        csv << checkatri.attributes.values_at(*all_column_names)
      end
    end
  end

  def self.import(file)
    require 'roo'
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by(id: row["id"]) || new
      product.attributes = row.to_hash
      product.save!

    end
  end

  def self.open_spreadsheet(file)
    require 'roo'
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


end

app/models/clienteremi.rb
class Clienteremi < ApplicationRecord
  has_many :remisions
    validates_presence_of :nombre, :apellidos, :empresa, :nit, :ciudad, :direccion, :telefono;


      def client_order
        "#{nombre}#{apellidos}. #{empresa}"
      end
end

app/models/componente.rb
class Componente < ApplicationRecord
  belongs_to :hojavida
end

app/models/hojavida.rb
class Hojavida < ApplicationRecord
  has_many :componentes, :dependent => :destroy
  has_many :archives, :dependent => :destroy
  has_many :permisos, :dependent => :destroy
  has_many :licenses, :dependent => :destroy

  validates_presence_of :nombre, :tipo, :marca, :modelo, :serial, :area_funcionamiento,:fecha_compra, :garantia, :proveedor, :pieza;
  accepts_nested_attributes_for :componentes,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :archives,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :permisos,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :licenses,reject_if: :all_blank,allow_destroy: true


    def self.to_csv(options ={})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |hojavida|
          csv << hojavida.attributes.values_at(*all_column_names)
        end
      end
    end

    def self.search(search)
      if search
        where( 'nombre LIKE ?', "%#{search}%")
      else
        all
      end
    end



end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :hojavida
end

app/models/permiso.rb
class Permiso < ApplicationRecord
  belongs_to :hojavida
end

app/models/remision.rb
class Remision < ApplicationRecord
  has_many :atriremis, :dependent => :destroy
  has_many :atrichecks, :dependent => :destroy

  belongs_to :clienteremi
  accepts_nested_attributes_for :atriremis,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |remision|
        csv << remision.attributes.values_at(*all_column_names)
      end
    end
  end

end

app/models/reporte.rb
class Reporte < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/remisions_controller.rb
class RemisionsController < ApplicationController

    def index
      @remisions = Remision.all.paginate(:page => params[:page], :per_page =>10)

      respond_to do |format|
          format.html
          format.csv { send_data @remisions.to_csv }
          format.xls do
            @remisions = Hojavida.all
          end## { send_data @products.to_csv(col_sep: "\t") }
      end

    end

    def show
      @remision = Remision.find(params[:id])
      respond_to do |format|
        format.html
        format.json
        format.pdf do
            render template: "remisions/pdfRemi", pdf: 'pdfRemi'
        end
      end
    end

    def new
      @remision = Remision.new
    end


    def edit
      @remision = Remision.find(params[:id])
    end

    def create
      @remision = Remision.new(remision_params)
      respond_to do |format|
        if @remision.save
          format.html { redirect_to @remision, notice: 'Remision creada correctamente.' }
          format.json { render :show, status: :created, location: @remision }
        else
          format.html { render :new }
          format.json { render json: @remision.errors, status: :unprocessable_entity }
        end
      end

    end

    def update
      @remision = Remision.find(params[:id])
      respond_to do |format|
        if @remision.update(remision_params)
          format.html { redirect_to @remision, notice: 'Remision actualizada correctamente.' }
          format.json { render :show, status: :ok, location: @remision }
        else
          format.html { render :edit }
          format.json { render json: @remision.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_remision
      @remision = Remision.find(params[:id])
    end

      # Never trust parameters from the scary internet, only allow the white list through.
      def remision_params
        params.require(:remision).permit(:fecha_expedicion,:fecha_vencimiento,:clienteremi_id,:nota,:valor_bruto,:descuento,:subtotal,:iva,:total,
        atriremis_attributes: [:id,:referencia, :descripcion, :lote, :cantidad, :unidad, :_destroy],
        atrichecks_attributes: [:id,:lote, :cantidad, :unidad,:checkatri_id,:_destroy])
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end

end

app/helpers/checkatris_helper.rb
module CheckatrisHelper
end

app/helpers/clienteremis_helper.rb
module ClienteremisHelper
end

app/helpers/hojavidas_helper.rb
module HojavidasHelper

  

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/views/remisions/_atrichecks_fields.html.erb
<div class="nested-fields">
  <div class="col-md-10" style = "float: left">
    <%= f.association :checkatri, label: "Productos" %>
  </div>
  <div class=" col-md-2" style = "float: left">
    <h5><%= f.input :lote %></h5>
  </div>
    <div class=" col-md-6" style = "float: left">
      <h5><%= f.input :cantidad %></h5>
    </div>
    <div class=" col-md-6" style = "float: left">
      <h5><%= f.input :unidad, :input_html => { :value => 'UND' }%></h5>
    </div>

    <div>
    <%= link_to_remove_association  "X",f,class:"btn btn-outline-danger" %>
      </div>
      <hr>
</div>

app/views/remisions/_atriremis_fields.html.erb
<div class="nested-fields">
  <div class=" col-md-2" style = "float: left">
    <h5><%= f.input :referencia %></h5>
  </div>
  <div class=" col-md-8" style = "float: left">
    <h5><%= f.input :descripcion %></h5>
  </div>
  <div class=" col-md-2" style = "float: left">
    <h5><%= f.input :lote %></h5>
  </div>
    <div class=" col-md-3" style = "float: left">
      <h5><%= f.input :cantidad %></h5>
    </div>
    <div class=" col-md-3" style = "float: left">
      <h5><%= f.input :unidad, :input_html => { :value => 'UND' }%></h5>
    </div>

    <div>
    <%= link_to_remove_association  "X",f,class:"btn btn-outline-danger" %>
      </div>
      <hr>
</div>

app/views/remisions/_form.html.erb
<%= simple_form_for(@remision) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


<center>
<div style="display:inline-block;" >
  <form>
        <div class="form-row">

          <div class="form-group col-md-12">
            <h5><%= f.input :fecha_expedicion %></h5>
          </div>

            <div class="form-group col-md-12">
              <h5>Cliente</h5>
              <%= collection_select(:remision,:clienteremi_id,Clienteremi.order(:nombre),:id,:client_order,{:prompt => 'Seleccionar cliente'},class:"custom-select col-md-12")%>
            </div>
          </div>
          <br>

          <div class="card text-center">
            <div class="card-header">
              <h4>Ingresar Productos</h4>
            </div>
            <div class="card-body">
              <div id='atributos'>
                <%= f.simple_fields_for :atriremis do |atriremi|%>
                <%=render 'atriremis_fields', :f => atriremi%>
                <%end%>
                <div class='links'>
                  <%= link_to_add_association 'Agregar', f, :atriremis,partial: 'atriremis_fields',class:"btn btn-outline-success"%>
                </div>
              </div>
            </div>
          </div>

          <hr>
          <br>
          <hr>
          <div class="card text-center">
            <div class="card-header">
            <h4>Buscar Productos</h4>
            </div>
            <div class="card-body">
            <div id='atributos'>
              <%= f.simple_fields_for :atrichecks do |atricheck|%>
              <%=render 'atrichecks_fields', :f => atricheck%>
              <%end%>
              <div class='links'>
                <%= link_to_add_association 'Agregar', f, :atrichecks,partial: 'atrichecks_fields',class:"btn btn-outline-success"%>
              </div>
            </div>
            </div>
          </div>
          <br>

        <hr>
        <div class="form-row">
            <div class="form-group col-md-12">
              <div class="shadow-none p-3 mb-5 bg-light rounded">
                <h5><%= f.input :nota %></h5>
              </div>
            </div>
      </div>

  </form>

  <%= f.button :submit,"Generar",class:"btn btn-success col-md-4" %>
</div>
</center>
<%end%>

app/views/remisions/edit.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Editar remision</h1>
  </center>
</div>
<%= render 'form', remision: @remision %>
<br>
<center>
<%= link_to '➜', @remision, class:"btn btn-primary col-md-2" %>
<%= link_to 'Cancelar', remisions_path, class:"btn btn-outline-secondary  col-md-2" %>
<br>
<hr>
</center>

app/views/remisions/index.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Informacion de remisiones</h1>
  </center>
</div>

<table class="table table-hover table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Remision Noº</th>
      <th>Fecha exp</th>
      <th>Cliente</th>
      <th>Nota</th>



      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>

    <div class="d-flex flex-row-reverse bd-highligth p-1">
        <%= link_to 'Nueva remisión', new_remision_path, class:"btn btn-success mr-2" %>
    </div>

    <% @remisions.each do |r| %>
    <tr>
      <td><%= r.id %></td>
        <td><%= r.fecha_expedicion %></td>
        <td><%= r.clienteremi_id %></td>
        <td><%= r.nota %></td>
        <td><%= link_to '➜',r,class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_remision_path(r), class:"btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="d-flex justify-content-center">
  <%=will_paginate @remision,renderer: WillPaginate::ActionView::BootstrapLinkRenderer,previous_label:"Anterior ",next_label:" Siguiente",
  inner_window: 1, outer_window: 0 %>
</div>
<br>

<footer><%= render "inicio/footer"%></footer>

app/views/remisions/new.html.erb
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div  class="shadow-lg p-3 mb-5 bg-white rounded">
      <center>
        <h1>Nueva remisión</h1>
      </center>
    </div>
    <br>

    <center>

      <%=render 'form'%>
      <br>
        <%= link_to 'Cancelar', remisions_path, class:"btn btn-outline-danger mr-2" %>
        <hr>
    </center>
  </body>
  <footer><%= render "inicio/footer"%></footer>
</html>

app/views/remisions/pdfRemi.pdf.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> RemisionSamaracosmetics</title>
    <%=wicked_pdf_stylesheet_link_tag 'pdf'%>
    </head>
  <body>
    <center>
      <%= wicked_pdf_image_tag '200elogo.png',style:"float:left; margin:30px;" %>
    <p style="float:left; margin:30px;"><b>Samara Cosmetics S.A.S</b><br>
    Cra 54 No 72a 65<br>Telefono:2258432 -4448438<br>info@samaracosmetics.com<br>IVA-REGIMEN COMUN<br>Agente retenedor</p>
    <br>
    <table border="1" style="margin:20px;">
			<tr>
				<th colspan="2" width="90%">Remisión<br> Noº <%= @remision.id %></th>
			</tr>
			<tr>
				<th colspan="2">&emsp; &emsp;--&emsp; &emsp; ORIGINAL&emsp; &emsp; -- &emsp; &emsp;</th>
			</tr>
			<tr>
				<td><center><b>Fecha Expedición</b><br><%= @remision.fecha_expedicion %></center></td>
			</tr>
		</table>
  </center>
  <div style="float:left;">
  <strong>Nombre :</strong>&nbsp;&nbsp;<%=@remision.clienteremi.nombre %>&nbsp;<%=@remision.clienteremi.apellidos%>
    &nbsp;&nbsp;&nbsp;&nbsp;<strong>Empresa :</strong>&nbsp;<%=@remision.clienteremi.empresa%>
      &nbsp;&nbsp;&nbsp;&nbsp;<strong>Nit :</strong>&nbsp;<%=@remision.clienteremi.nit%>
        &nbsp;&nbsp;<strong>Ciudad :</strong>&nbsp;<%=@remision.clienteremi.ciudad%>
          &nbsp;&nbsp;<strong>Direccion :</strong>&nbsp;<%=@remision.clienteremi.direccion%>
            &nbsp;&nbsp;<strong>Telefono :</strong>&nbsp;<%=@remision.clienteremi.telefono%>
    </div>
    <br>
    <table border>
  <tr>
    <th width="10%">Referencia</th>
    <th width="60%">Descripcion</th>
    <th width="10%">Lote</th>
    <th width="8%">Cantidad</th>
    <th width="8%">Unidad</th>
  </tr>
  <% @remision.atrichecks.each do |atricheck|%>
  <tr>
    <td><center><%=atricheck.checkatri.try(:referencia)%></center></td>
    <td><center><%=atricheck.checkatri.try(:descripcion)%></center></td>
    <td><center><%=atricheck.lote%></center></td>
    <td><center><%=atricheck.cantidad%></center></td>
    <td><center><%=atricheck.unidad%></center></td>
  </tr>
  <%end%>

  <% @remision.atriremis.each do |atriremi|%>
  <tr>
    <td><center><%= atriremi.referencia%></center></td>
    <td><center><%=atriremi.descripcion%></center></td>
    <td><center><%=atriremi.lote%></center></td>
    <td><center><%=atriremi.cantidad%></center></td>
    <td><center><%=atriremi.unidad%></center></td>
  </tr>
  <%end%>
</table>
<table border>
	<tr>
		<td rowspan=2 width="1000px">&nbsp;<b>NOTA :</b> &nbsp;&nbsp;<%= @remision.nota%></td>

	</tr>
</table>
<center>
  <div>
    <p style="float:left;"><b>____________________ <br>Vendedor.</b> <br>Nit: 900.313.153-7</p>
    <p style="float:left;"><b>&nbsp; ____________________<br>Recib/Cliente.</b> <br>Nit/Cc: <%=@remision.clienteremi.nit%></p>
  </div>
      <p><b>Nuestras marcas :</b>
        <%= wicked_pdf_image_tag 'mawie150.png',style:"float:ringt; margin:5px;" %>
        <%= wicked_pdf_image_tag 'Isabely50.png'%>
        <%= wicked_pdf_image_tag 'lorhan.png' %></p>
</center>

  </body>
</html>

app/views/remisions/show.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Detalles del registro</h1>
  </center>
</div>
<center>



<p>
  <strong>Fecha Expedicion:</strong>
  <%= @remision.fecha_expedicion %>
</p>
<p>
  <strong>Cliente :</strong>
  <%=@remision.clienteremi.nombre %>&nbsp;&nbsp;
  <strong>Apellidos :</strong><%=@remision.clienteremi.apellidos%>
  &nbsp;&nbsp;<strong>Empresa :</strong><%=@remision.clienteremi.empresa%>
  &nbsp;&nbsp;<strong>Nit :</strong><%=@remision.clienteremi.nit%>
  &nbsp;&nbsp;<strong>Ciudad :</strong><%=@remision.clienteremi.ciudad%></p>



<% @remision.atriremis.each do |atriremi|%>
<p><strong>Referencia : </strong><%= atriremi.referencia%>
&nbsp;&nbsp;<strong>Descripcion :</strong><%=atriremi.descripcion%>
&nbsp;&nbsp;<strong>Lote :</strong><%=atriremi.lote%>
&nbsp;&nbsp;<strong>Cantidad :</strong><%=atriremi.cantidad%>
&nbsp;&nbsp;<strong>Unidad :</strong><%=atriremi.unidad%></p>
<%end%>


<% @remision.atrichecks.each do |atricheck|%>
<p>
&nbsp;&nbsp;<strong>Referencia :</strong><%=atricheck.checkatri.try(:referencia)%>
&nbsp;&nbsp;<strong>Descripcion :</strong><%=atricheck.checkatri.try(:descripcion)%>
&nbsp;&nbsp;<strong>Lote :</strong><%=atricheck.lote%>
&nbsp;&nbsp;<strong>Cantidad :</strong><%=atricheck.cantidad%>
&nbsp;&nbsp;<strong>Unidad :</strong><%=atricheck.unidad%></p>
<%end%>

<p>
  <strong>Nota:</strong>
  <%= @remision.nota %>
</p>

    <%= link_to 'Atras', remisions_path,class:"btn btn-info" %>
    <%= link_to 'Editar', edit_remision_path(@remision),class:"btn btn-warning" %>
    <%= link_to 'Nueva remision', new_remision_path,class:"btn btn-success" %>
    <br>
    <hr>
    <div class="col-md-6">
      <div class="shadow-lg p-3 mb-5 bg-white ">
        <center>
      <h3>Generar Remision</h3>
      <%= link_to 'PDF',remision_path(@remision, format: "pdf"), class:"btn btn-outline-danger mr-2" %>
      </center>
    </div>
    </div>
</center>