config/routes.rb
Rails.application.routes.draw do
  resources :checkatris
  resources :reportes
  resources :clienteremis
  resources :licenses
  resources :hojavidas
  resources :remisions, except: [:delete]
  devise_for :users

  root 'inicio#index'

  resources :checkatris do
    collection do
      post :import
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :hojavida
  has_one_attached :file
end

app/models/atricheck.rb
class Atricheck < ApplicationRecord
  belongs_to :checkatri
  belongs_to :remision


end

app/models/atriremi.rb
class Atriremi < ApplicationRecord
  belongs_to :remision

end

app/models/checkatri.rb
class Checkatri < ApplicationRecord
  has_many :atrichecks

  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true


  def name
    "#{referencia} - #{descripcion}"
  end

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |checkatri|
        csv << checkatri.attributes.values_at(*all_column_names)
      end
    end
  end

  def self.import(file)
    require 'roo'
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by(id: row["id"]) || new
      product.attributes = row.to_hash
      product.save!

    end
  end

  def self.open_spreadsheet(file)
    require 'roo'
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


end

app/models/clienteremi.rb
class Clienteremi < ApplicationRecord
  has_many :remisions
    validates_presence_of :nombre, :apellidos, :empresa, :nit, :ciudad, :direccion, :telefono;


      def client_order
        "#{nombre}#{apellidos}. #{empresa}"
      end
end

app/models/componente.rb
class Componente < ApplicationRecord
  belongs_to :hojavida
end

app/models/hojavida.rb
class Hojavida < ApplicationRecord
  has_many :componentes, :dependent => :destroy
  has_many :archives, :dependent => :destroy
  has_many :permisos, :dependent => :destroy
  has_many :licenses, :dependent => :destroy

  validates_presence_of :nombre, :tipo, :marca, :modelo, :serial, :area_funcionamiento,:fecha_compra, :garantia, :proveedor, :pieza;
  accepts_nested_attributes_for :componentes,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :archives,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :permisos,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :licenses,reject_if: :all_blank,allow_destroy: true


    def self.to_csv(options ={})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |hojavida|
          csv << hojavida.attributes.values_at(*all_column_names)
        end
      end
    end

    def self.search(search)
      if search
        where( 'nombre LIKE ?', "%#{search}%")
      else
        all
      end
    end



end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :hojavida
end

app/models/permiso.rb
class Permiso < ApplicationRecord
  belongs_to :hojavida
end

app/models/remision.rb
class Remision < ApplicationRecord
  has_many :atriremis, :dependent => :destroy
  has_many :atrichecks, :dependent => :destroy

  belongs_to :clienteremi
  accepts_nested_attributes_for :atriremis,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |remision|
        csv << remision.attributes.values_at(*all_column_names)
      end
    end
  end

end

app/models/reporte.rb
class Reporte < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end

end

app/helpers/checkatris_helper.rb
module CheckatrisHelper
end

app/helpers/clienteremis_helper.rb
module ClienteremisHelper
end

app/helpers/hojavidas_helper.rb
module HojavidasHelper

  

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/views/Partials/_nav.html.erb
<% if user_signed_in?%>
<div class="pos-f-t" >
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h3">Samara Cosmetics</h5>
      <span class="text-muted h5">Sistema integrado para el area de sistemas</span>


        <nav class="navbar navbar-expand-lg navbar-light bg-light" >

          <div class="navbar-nav mr-auto text-center">
            <%= link_to "Inicio", root_path,{class:"btn btn-outline-primary mr-4"} %>
            <%= link_to "Registro equipo", hojavidas_path,class:"btn btn-outline-success mr-2" %>

            <li class="nav-item dropdown">
              <button class="dropdown-toggle btn btn-outline-success mr-2" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Remisiones</button>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Generar remision', new_remision_path, class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Crear producto', new_checkatri_path, class:"dropdown-item" %>
                  <%= link_to 'Crear cliente', new_clienteremi_path, class:"dropdown-item" %>
                  <%= link_to 'Remisiones generadas', remisions_path, class:"dropdown-item" %>
                </div>
           </li>
           <%= link_to "Reporte problema", new_reporte_path,{class:"btn btn-outline-success mr-2"} %>
          </div>

            <div class="d-flex flex-row justify-content-center">

              <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger mr-2"%>
            </div>

        </nav>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
<%else%>
<div class="pos-f-t" >
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h3">Samara Cosmetics</h5>
      <span class="text-muted h5">Sistema integrado para la empresa Samara Cosmetics S.A</span>


        <nav class="navbar navbar-expand-lg navbar-light bg-light ">

          <div class="navbar-nav mr-auto text-center">
            <%= link_to "Inicio", root_path,{class:"btn btn-outline-primary mr-4"} %>
            <%= link_to "Registro equipo", hojavidas_path,{class:"btn btn-outline-success mr-2"} %>

            <li class="nav-item dropdown">
              <button class="dropdown-toggle btn btn-outline-success mr-2" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Remisiones</button>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Generar remision', new_remision_path, class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Crear producto', new_checkatri_path, class:"dropdown-item" %>
                  <%= link_to 'Crear cliente', new_clienteremi_path, class:"dropdown-item" %>
                  <%= link_to 'Remisiones generadas', remisions_path, class:"dropdown-item" %>
                </div>
           </li>
           <%= link_to "Reporte problema", new_reporte_path,{class:"btn btn-outline-success mr-2"} %>

          </div>

            <div class="d-flex flex-row justify-content-center">
              <%= link_to "Iniciar sesion", new_user_session_path,{class:"btn btn-primary mr-2"}%>
            </div>

        </nav>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
<%end%>

app/views/Partials/pdf.pdf.erb
    <center>
    <h2>Inventario equipos Samara Cosmetics</h2>
    </center>
    <table class="table">
      <thead>
        <tr>
          <th style="width: 200px;"  bgcolor="gray" >Nombre</th>
          <th style="width: 150px;" bgcolor="gray">Marca</th>
          <th style="width: 150px;" bgcolor="gray">Serial</th>
          <th style="width: 200px;" bgcolor="gray">Area funcionamiento</th>
          <th style="width: 200px;" bgcolor="gray">Fecha compra</th>
          <th style="width: 200px;" bgcolor="gray">Fecha vencimiento garantia</th>
          <th style="width: 150px;" bgcolor="gray">Precio</th>
        </tr>
      </thead>

      <tbody>
        <% @hojavidas.each do |hojavida|%>
        <tr>
          <td><%= hojavida.nombre %></td>
          <td><%= hojavida.marca %></td>
          <td><%= hojavida.serial %></td>
          <td><%= hojavida.area_funcionamiento %></td>
          <td><%= hojavida.fecha_compra %></td>
          <td><%= hojavida.garantia %></td>
          <td><%= hojavida.precio %></td>
        </tr>
        <% end %>
      </tbody>

    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaSamara</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "Partials/nav"%>
      <%if notice%>
        <p class="alert alert-success"><%= notice %></p>
      <%end%>
      <%if alert%>
        <p class="alert alert-danger"><%= alert %></p>
      <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> InventarioSamaracosmetics</title>
    <%=wicked_pdf_stylesheet_link_tag 'pdf'%>
  <body>
    <%=yield%>
  </body>
</html>