config/routes.rb
Rails.application.routes.draw do
  resources :checkatris
  resources :reportes
  resources :clienteremis
  resources :licenses
  resources :hojavidas
  resources :remisions, except: [:delete]
  devise_for :users

  root 'inicio#index'

  resources :checkatris do
    collection do
      post :import
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :hojavida
  has_one_attached :file
end

app/models/atricheck.rb
class Atricheck < ApplicationRecord
  belongs_to :checkatri
  belongs_to :remision


end

app/models/atriremi.rb
class Atriremi < ApplicationRecord
  belongs_to :remision

end

app/models/checkatri.rb
class Checkatri < ApplicationRecord
  has_many :atrichecks

  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true


  def name
    "#{referencia} - #{descripcion}"
  end

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |checkatri|
        csv << checkatri.attributes.values_at(*all_column_names)
      end
    end
  end

  def self.import(file)
    require 'roo'
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by(id: row["id"]) || new
      product.attributes = row.to_hash
      product.save!

    end
  end

  def self.open_spreadsheet(file)
    require 'roo'
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


end

app/models/clienteremi.rb
class Clienteremi < ApplicationRecord
  has_many :remisions
    validates_presence_of :nombre, :apellidos, :empresa, :nit, :ciudad, :direccion, :telefono;


      def client_order
        "#{nombre}#{apellidos}. #{empresa}"
      end
end

app/models/componente.rb
class Componente < ApplicationRecord
  belongs_to :hojavida
end

app/models/hojavida.rb
class Hojavida < ApplicationRecord
  has_many :componentes, :dependent => :destroy
  has_many :archives, :dependent => :destroy
  has_many :permisos, :dependent => :destroy
  has_many :licenses, :dependent => :destroy

  validates_presence_of :nombre, :tipo, :marca, :modelo, :serial, :area_funcionamiento,:fecha_compra, :garantia, :proveedor, :pieza;
  accepts_nested_attributes_for :componentes,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :archives,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :permisos,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :licenses,reject_if: :all_blank,allow_destroy: true


    def self.to_csv(options ={})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |hojavida|
          csv << hojavida.attributes.values_at(*all_column_names)
        end
      end
    end

    def self.search(search)
      if search
        where( 'nombre LIKE ?', "%#{search}%")
      else
        all
      end
    end



end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :hojavida
end

app/models/permiso.rb
class Permiso < ApplicationRecord
  belongs_to :hojavida
end

app/models/remision.rb
class Remision < ApplicationRecord
  has_many :atriremis, :dependent => :destroy
  has_many :atrichecks, :dependent => :destroy

  belongs_to :clienteremi
  accepts_nested_attributes_for :atriremis,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :atrichecks,reject_if: :all_blank,allow_destroy: true

  def self.to_csv(options ={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |remision|
        csv << remision.attributes.values_at(*all_column_names)
      end
    end
  end

end

app/models/reporte.rb
class Reporte < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  before_action :set_license, only: [:show, :edit, :update, :destroy]

  # GET /licenses
  # GET /licenses.json
  def index
    @licenses = License.all
  end

  # GET /licenses/1
  # GET /licenses/1.json
  def show
  end

  # GET /licenses/new
  def new
    @license = License.new
  end

  # GET /licenses/1/edit
  def edit
  end

  # POST /licenses
  # POST /licenses.json
  def create
    @license = License.new(license_params)

    respond_to do |format|
      if @license.save
        format.html { redirect_to @license, notice: 'License was successfully created.' }
        format.json { render :show, status: :created, location: @license }
      else
        format.html { render :new }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /licenses/1
  # PATCH/PUT /licenses/1.json
  def update
    respond_to do |format|
      if @license.update(license_params)
        format.html { redirect_to @license, notice: 'License was successfully updated.' }
        format.json { render :show, status: :ok, location: @license }
      else
        format.html { render :edit }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /licenses/1
  # DELETE /licenses/1.json
  def destroy
    @license.destroy
    respond_to do |format|
      format.html { redirect_to licenses_url, notice: 'License was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = License.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_params
      params.require(:license).permit(:nombre, :serial, :fecha_vencimiento, :hojavida_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end

end

app/helpers/checkatris_helper.rb
module CheckatrisHelper
end

app/helpers/clienteremis_helper.rb
module ClienteremisHelper
end

app/helpers/hojavidas_helper.rb
module HojavidasHelper

  

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/views/inicio/_footer.html.erb
<div class="card text-center">
  <div class="card-body">
    <p class="card-text">Sistema creado y puesto en desarrollo internamente en la empresa Samara Cosmetics S.A</p>
    <a href="#" class="btn btn-outline-secondary" data-toggle="modal" data-target="#exampleModalCenter">Desarrollado por :</a>
  </div>
  <div class="card-footer text-muted" style="background-color:#282c31">
    2018 © Samaracosmetics.com. Todos los derechos reservados.
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalCenterTitle">Sistema desarrollado y aprobado</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Creditos</h5>
        <p>
            Nombre : Stiven Arteaga Espitia<br>
            Cargo  : Tecnologo y asistente de sistemas<br>
            Telefono : 4448438 ext 129 <br>
            Correo : stiven.arteaga@Samaracosmetics.com<br>
        </p>
        <p>Inquietud o interes, atendidos directamente al correo electronico.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/inicio/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%=image_tag 'logs.png', :class=>"d-block w-100", :alt=>"First slide"%>
    </div>
    <div class="carousel-item">
      <%=image_tag 'log2.png', :class=>"d-block w-100", :alt=>"Second slide"%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="card">
  <div class="card-header" style="background-color:#282c31" >
    <h5 style="color:#FFFFFF";>Acerca del sistema</h5>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Sistema informatico creado con el fin de llevar control de inventarios de computo u otros dispositivos, busca
         recolectar toda la informacion de un equipo para hacer un control previo respectivamente.<br>
         Permitira a los empleados de la empresa reportar un problema con cualquier equipo tecnologico,
         dejando en evidencia las fechas y el problema que presentan.<br>
         Facilidad para ingresar y generar una remision dado el caso, dando un mejor uso y representacion de las remisiones.
      </p>
      <footer class="blockquote-footer">Samara Cosmetics S.A, siendo mejores cada dia<cite title="Source Title"></cite></footer>
    </blockquote>
  </div>
</div>
<br>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Ir al registro de computo</h5>
        <p class="card-text">Registra el estado o si se ah hecho algun cambio en el equipo. Registralo !</p>
        <%= link_to "Ir al registro", hojavidas_path,{class:"btn btn-outline-success"} %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Tienes algun problema ? Reportalo</h5>
        <p class="card-text">Si presentas algun problema en general de soporte que involucra al area de sistemas, crea un reporte</p>
        <%= link_to "Hacer reporte", new_reporte_path,{class:"btn btn-outline-success"} %>
      </div>
    </div>
  </div>
</div>
<br>
<%= render 'footer'%>

app/views/licenses/_form.html.erb
<%= simple_form_for(@license) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :serial %>
    <%= f.input :fecha_vencimiento %>
    <%= f.association :hojavida %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/licenses/edit.html.erb
<h1>Editing License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Show', @license %> |
<%= link_to 'Back', licenses_path %>

app/views/licenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Licenses</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Serial</th>
      <th>Fecha vencimiento</th>
      <th>Hojavida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.nombre %></td>
        <td><%= license.serial %></td>
        <td><%= license.fecha_vencimiento %></td>
        <td><%= license.hojavida %></td>
        <td><%= link_to 'Show', license %></td>
        <td><%= link_to 'Edit', edit_license_path(license) %></td>
        <td><%= link_to 'Destroy', license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New License', new_license_path %>

app/views/licenses/new.html.erb
<h1>New License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Back', licenses_path %>

app/views/licenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @license.nombre %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @license.serial %>
</p>

<p>
  <strong>Fecha vencimiento:</strong>
  <%= @license.fecha_vencimiento %>
</p>

<p>
  <strong>Hojavida:</strong>
  <%= @license.hojavida %>
</p>

<%= link_to 'Edit', edit_license_path(@license) %> |
<%= link_to 'Back', licenses_path %>