config/routes.rb
Rails.application.routes.draw do
  resources :checkatris
  resources :reportes
  resources :clienteremis
  resources :licenses
  resources :hojavidas
  resources :remisions, except: [:delete]
  devise_for :users

  root 'inicio#index'

  resources :checkatris do
    collection do
      post :import
    end
  end

end

app/models/hojavida.rb
class Hojavida < ApplicationRecord
  has_many :componentes, :dependent => :destroy
  has_many :archives, :dependent => :destroy
  has_many :permisos, :dependent => :destroy
  has_many :licenses, :dependent => :destroy

  validates_presence_of :nombre, :tipo, :marca, :modelo, :serial, :area_funcionamiento,:fecha_compra, :garantia, :proveedor, :pieza;
  accepts_nested_attributes_for :componentes,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :archives,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :permisos,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :licenses,reject_if: :all_blank,allow_destroy: true


    def self.to_csv(options ={})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |hojavida|
          csv << hojavida.attributes.values_at(*all_column_names)
        end
      end
    end

    def self.search(search)
      if search
        where( 'nombre LIKE ?', "%#{search}%")
      else
        all
      end
    end



end

app/controllers/hojavidas_controller.rb
class HojavidasController < ApplicationController
    before_action :set_hojavida, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    helper_method :sort_column, :sort_direction
  # GET /hojavidas
  # GET /hojavidas.json
  def index
    @hojavidas = Hojavida.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page =>7)
    # .where("name LIKE ?", "%#{params[:search]}%")
    # search(params[:search])
    #.where(nombre: 'Computador')

    respond_to do |format|
      format.html
      format.json
      format.pdf do
        @hojavidas = Hojavida.all.order(:nombre)
        render template: "Partials/pdf", pdf: 'Pdf',layout: 'pdf.html'
      end
      format.csv {send_data @hojavidas.to_csv}
      format.xls do
        @hojavidas = Hojavida.all.order(:nombre)
      end# {send_data @hojavidas.to_csv(col_sep: "\t")}

    end
  end

  # GET /hojavidas/1
  # GET /hojavidas/1.
  def show
  end

  # GET /hojavidas/new
  def new
    @hojavida = Hojavida.new
  end

  # GET /hojavidas/1/edit
  def edit
  end

  # POST /hojavidas
  # POST /hojavidas.json
  def create
    @hojavida = Hojavida.new(hojavida_params)

    respond_to do |format|
      if @hojavida.save
        format.html { redirect_to @hojavida, notice: 'Registro creado correctamente.' }
        format.json { render :show, status: :created, location: @hojavida }
      else
        format.html { render :new }
        format.json { render json: @hojavida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hojavidas/1
  # PATCH/PUT /hojavidas/1.json
  def update
    respond_to do |format|
      if @hojavida.update(hojavida_params)
        format.html { redirect_to @hojavida, notice: 'Registro actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @hojavida }
      else
        format.html { render :edit }
        format.json { render json: @hojavida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hojavidas/1
  # DELETE /hojavidas/1.json
  def destroy
    @hojavida.destroy
    respond_to do |format|
      format.html { redirect_to hojavidas_url, notice: 'Registro eliminado correctamente..' }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Hojavida.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_hojavida
      @hojavida = Hojavida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hojavida_params
      params.require(:hojavida).permit(:nombre, :tipo, :marca, :modelo, :serial, :precio ,:area_funcionamiento, :descripcion, :precauciones, :fecha_compra, :garantia, :proveedor, :pieza,
      componentes_attributes: [:id,:nombre_componente,:serial, :_destroy],archives_attributes: [:id,:nombre_archivo,:file,:_destroy],
      permisos_attributes: [:id,:nombre ,:serial,:fecha_vencimiento,:_destroy])
    end
end

app/helpers/hojavidas_helper.rb
module HojavidasHelper

  

end

app/views/hojavidas/_archives_fields.html.erb
<div class="nested-fields">
    <div class="form-check-inline col-form-label">
      <h5><%= f.input :nombre_archivo %></h5>
    </div>
    <div class="form-check-inline">
      <div class="custom-file">
        <h5><%= f.label :Archivo %></h5>
        <%= f.file_field :file%>
      </div>
    </div>

    <div class=" form-check-inline">
      <%= link_to_remove_association  "X",f,class:"btn btn-outline-danger"%>
    </div>
    <p>



</div>

app/views/hojavidas/_componentes_fields.html.erb
<div class="nested-fields">
    <div class="form-check-inline col-form-label">
      <h5><%= f.input :nombre_componente %></h5>
    </div>
    <div class="form-check-inline ">
      <h5><%= f.input :serial%></h5>
    </div>

    <div class=" form-check-inline">
      <%= link_to_remove_association  "X",f,class:"btn btn-outline-danger"%>
    </div>


</div>

app/views/hojavidas/_form.html.erb
<%= simple_form_for(@hojavida) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs ">
    <div class="col-md-10  ">
    <h5> <%= f.input :nombre, :hint=>"Nombre equio ejm: Computador"%></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :tipo %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :marca %></h5>
    </div>
    <div class="col-md-10 ">
    <h5><%= f.input :modelo %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :serial %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :precio %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :area_funcionamiento %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :descripcion, :hint=>"Que funcionalidad desarrolla el equipo" %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :precauciones %></h5>
    </div>
    <div class="col-md-10 ">
    <h5><%= f.input :fecha_compra, as: :date,start_year: Date.today.year-28,
                                end_year: Date.today.year,
                                order:[:year,:month, :day],:hint=>"Fecha en que se recibio el equipo" %></h5>
    </div>
    <div class="col-md-10 ">
    <h5><%= f.input :garantia, as: :date,start_year: Date.today.year-10,
                                end_year: Date.today.year+20,
                                order:[:year,:month, :day],:hint=>"Hasta que fecha esta vigente la garantia" %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :proveedor %></h5>
    </div>
    <div class="col-md-10 ">
      <h5><%= f.input :pieza, :hint=>"Piezas remplazadas" %></h5>
    </div>
  </div>
<center>

  <div class="row col-md-10">

    <div class="col-md-12">
      <div class="shadow-lg p-3 mb-5 bg-white rounded">
      <h3>Añadir Licencias</h3>
      <div id='permisos'>

        <%= f.simple_fields_for :permisos do |permiso|%>
        <%=render 'permisos_fields', :f => permiso%>
        <%end%>
        <div class='links'>
          <br>
          <%= link_to_add_association 'Agregar', f, :permisos,partial: 'permisos_fields',class:"btn btn-outline-info"%>
        </div>
      </div>
    </div>
    </div>
  </div>


  <div class="row col-md-12">

    <div class="col-md-6">
      <div class="shadow-lg p-3 mb-5 bg-white rounded">
      <h3>Añadir componentes del equipo</h3>
      <div id='componentes'>

        <%= f.simple_fields_for :componentes do |componente|%>
        <%=render 'componentes_fields', :f => componente%>
        <%end%>
        <div class='links'>
          <br>
          <%= link_to_add_association 'Agregar', f, :componentes,partial: 'componentes_fields',class:"btn btn-outline-info"%>
        </div>
      </div>
    </div>
    </div>

    <div class="col-md-6 ">
      <div class="shadow-lg p-3 mb-5 bg-white rounded">
      <h3>Añadir Archivos del equipo</h3>
      <div id='archives'>

        <%= f.simple_fields_for :archives do |archive|%>
        <%=render 'archives_fields', :f => archive%>
        <%end%>
        <div class='links'>
          <br>
          <%= link_to_add_association 'Agregar', f, :archives,partial: 'archives_fields',class:"btn btn-outline-info"%>
        </div>
      </div>
    </div>
    </div>

  </div>

<br>
  <form actions="index">
    <%= f.button :submit,"Guardar",class:"btn btn-success col-md-4" %>
  </form>
<% end %>
</center>

app/views/hojavidas/_permisos_fields.html.erb
<div class="nested-fields">
    <div class="form-check-inline col-form-label">
      <h5><%= f.input :nombre %></h5>
    </div>
    <div class="form-check-inline ">
      <h5><%= f.input :serial%></h5>
    </div>
    <div class=" form-check-inline">
      <%= link_to_remove_association  "X",f,class:"btn btn-outline-danger"%>
    </div>
    <div class="col-md-10 ">
    <h5><%= f.input :fecha_vencimiento, as: :date,start_year: Date.today.year-10,
                                end_year: Date.today.year+50,
                                order:[:year,:month, :day]%></h5>
    </div>


</div>

app/views/hojavidas/edit.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Editar registro</h1>
  </center>
</div>
<%= render 'form', hojavida: @hojavida %>
<br>
<center>
<%= link_to '➜', @hojavida, class:"btn btn-primary col-md-2" %>
<%= link_to 'Cancelar', hojavidas_path, class:"btn btn-outline-secondary  col-md-2" %>
<br>
<hr>
</center>

app/views/hojavidas/index.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Informacion de equipos</h1>
  </center>
</div>

<table class="table table-hover table-striped">
  <thead class="thead-dark">
    <tr>
      <th><%= sortable "nombre" %></th>
      <th>Tipo</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Serial</th>
      <th>Area funcionamiento</th>
      <th><%= sortable "fecha_compra" %></th>
      <th>Fecha vencimiento garantia</th>
      <th><%= sortable "proveedor" %></th>
      <th>Piezas remplazadas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <center>
    <div class="col-md-4 ">
        <div class="d-flex justify-content-between">
              <%= form_tag hojavidas_path, :method => 'get', :id => "hojavidas_search" do %>
                <%= text_field_tag :search, params[:search],class:"form-control mr-sm-2", placeholder:"Buscar..." %>
                <%= submit_tag "Buscar", :name => nil,type:"hidden" %>
              <% end %>

        </div>
    </div>
    </center>
    <div class="d-flex flex-row-reverse bd-highligth p-1">
        <%= link_to 'Nuevo registro', new_hojavida_path, class:"btn btn-success mr-2" %>
        <%= link_to 'PDF', hojavidas_path(format: "pdf"), class:"btn btn-outline-danger mr-2" %>
        <%= link_to 'Excel', hojavidas_path(format: "xls"), class:"btn btn-outline-success mr-2" %>
    </div>

    <% @hojavidas.each do |hojavida| %>
      <tr>
        <td><%= hojavida.nombre %></td>
        <td><%= hojavida.tipo %></td>
        <td><%= hojavida.marca %></td>
        <td><%= hojavida.modelo %></td>
        <td><%= hojavida.serial %></td>
        <td><%= hojavida.area_funcionamiento %></td>
        <td><%= hojavida.fecha_compra %></td>
        <td><%= hojavida.garantia %></td>
        <td><%= hojavida.proveedor %></td>
        <td><%= hojavida.pieza %></td>
        <td><%= link_to '➜', hojavida,class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_hojavida_path(hojavida), class:"btn btn-warning" %></td>
        <td><%= link_to 'X', hojavida, method: :delete, data: {title:'Eliminar',
          confirm: 'Esta seguro de eliminar el registro?',cancel:'Cancelar',commit:'Eliminar'}, class:"btn btn-outline-danger " %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="d-flex justify-content-center">
  <%=will_paginate @hojavida,renderer: WillPaginate::ActionView::BootstrapLinkRenderer,previous_label:"Anterior ",next_label:" Siguiente",
  inner_window: 1, outer_window: 0 %>
</div>

<br>
<footer><%= render 'inicio/footer'%></footer>

app/views/hojavidas/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">Tipo</Data></Cell>
        <Cell><Data ss:Type="String">Marca</Data></Cell>
        <Cell><Data ss:Type="String">Modelo</Data></Cell>
        <Cell><Data ss:Type="String">Serial</Data></Cell>
        <Cell><Data ss:Type="String">Area funcionamiento</Data></Cell>
        <Cell><Data ss:Type="String">Fecha compra</Data></Cell>
        <Cell><Data ss:Type="String">Fecha vencimiento garantia</Data></Cell>
        <Cell><Data ss:Type="String">Precio</Data></Cell>
      </Row>
    <% @hojavidas.each do |hojavida| %>
      <Row>
        <Cell><Data ss:Type="String"><%= hojavida.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.tipo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.marca %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.modelo%></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.serial %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.area_funcionamiento %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.fecha_compra %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.garantia %></Data></Cell>
        <Cell><Data ss:Type="String"><%= hojavida.precio %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/hojavidas/new.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Nuevo registro</h1>
  </center>
</div>

<%= render 'form', hojavida: @hojavida %>
<br>
<center>
<%= link_to 'Cancelar', hojavidas_path, class:"btn btn-outline-secondary  col-md-4" %>
<br>
<hr>
</center>

app/views/hojavidas/show.html.erb
<div  class="shadow-lg p-3 mb-5 bg-white rounded">
  <center>
    <h1>Detalles del registro</h1>
  </center>
</div>
<center>
<p>
  <strong>Nombre:</strong>
  <%= @hojavida.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @hojavida.tipo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @hojavida.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @hojavida.modelo %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @hojavida.serial %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @hojavida.precio %>
</p>

<p>
  <strong>Area funcionamiento:</strong>
  <%= @hojavida.area_funcionamiento %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @hojavida.descripcion %>
</p>

<p>
  <strong>Precauciones:</strong>
  <%= @hojavida.precauciones %>
</p>

<p>
  <strong>Fecha compra:</strong>
  <%= @hojavida.fecha_compra %>
</p>

<p>
  <strong>Garantia:</strong>
  <%= @hojavida.garantia %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @hojavida.proveedor %>
</p>

<p>
  <strong>Pieza:</strong>
  <%= @hojavida.pieza %>
</p>
        <h4><strong>Licencias :</strong></h4>
        <p>
          <% @hojavida.permisos.each do |permiso|%>
          <p><strong>Nombre : </strong> <%= permiso.nombre%> &nbsp;&nbsp;<strong>Serial : </strong><%=permiso.serial%>
          &nbsp;&nbsp;<strong>Fecha vencimiento : </strong><%=permiso.fecha_vencimiento%> </p>

          <%end%>
        </p>

        <h4><strong>Componentes del equipo :</strong></h4>
        <p>
          <% @hojavida.componentes.each do |componente|%>
          <p><strong>Nombre : </strong> <%= componente.nombre_componente%>&nbsp;&nbsp; <strong>Serial : </strong><%=componente.serial%></p>
          <%end%>
        </p>

        <h4><strong>Archivos:</strong></h4>
        <p>
          <% @hojavida.archives.each do |archive|%>
          <p><strong>Nombre : </strong> <%= archive.nombre_archivo%> <%=link_to "Archivo",archive.file %></p>
          <%end%>
        </p>



          <h2>Licencias</h2>
          <% if @hojavida.licenses.any? %>
          <ul>
           <% @hojavida.licenses.each do |license| %>
          <li><%= link_to license, license %></li>
           <% end %>
          </ul>
          <% else %>
          <p>Ninguna disponible</p>
          <% end %>



    <%= link_to 'Editar', edit_hojavida_path(@hojavida),class:"btn btn-warning" %>
    <%= link_to 'Atras', hojavidas_path,class:"btn btn-primary" %>
    <br>
    <hr>
</center>